In [9]:
import numpy as np

In [10]:
def possible(x, y, n):
    global grid
    for i in range(9):
        if grid[i][y] == n:
            return False
    for j in range(9):
        if grid[x][j] == n:
            return False
    start_x = (x//3) * 3
    start_y = (y//3) * 3
    for i in range(start_x, start_x+3):
        for j in range(start_y, start_y+3):
            if grid[i][j] == n:
                return False
    return True

In [13]:
def sudoku_solver():
    global grid
    for row in range(9):
        for col in range(9):
            if grid[row][col] == 0:
                for n in range(1, 10):
                    if possible(row, col, n):
                        grid[row][col] = n
                        sudoku_solver()
                        grid[row][col] = 0
                return
    print(grid)
    input("more?")

In [14]:
grid = np.array([[5, 3, 0, 0, 7, 0, 0, 0, 0],
                 [6, 0, 0, 1, 9, 5, 0, 0, 0],
                 [0, 9, 8, 0, 0, 0, 0, 6, 0],
                 [8, 0, 0, 0, 6, 0, 0, 0, 3],
                 [4, 0, 0, 8, 0, 3, 0, 0, 1],
                 [7, 0, 0, 0, 2, 0, 0, 0, 6],
                 [0, 6, 0, 0, 0, 0, 2, 8, 0],
                 [0, 0, 0, 4, 1, 9, 0, 0, 5],
                 [0, 0, 0, 0, 8, 0, 0, 7, 9]])
sudoku_solver()

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
more?


In [17]:
%%time
import numpy as np


def possible(grid, x, y, n):
    #global grid
    for i in range(9):
        if grid[i][y] == n:
            return False
    for j in range(9):
        if grid[x][j] == n:
            return False
    start_x = (x//3) * 3
    start_y = (y//3) * 3
    for i in range(start_x, start_x+3):
        for j in range(start_y, start_y+3):
            if grid[i][j] == n:
                return False
    return True


def completed(grid):
    #global grid
    for i in range(9):
        for j in range(9):
            if grid[i][j] == 0:
                return False
    return True


def sudoku_solver(grid):
    #global grid
    for row in range(9):
        for col in range(9):
            if grid[row][col] == 0:
                for n in range(1, 10):
                    if possible(grid, row, col, n):
                        grid[row][col] = n
                        if completed(grid):
                            print(grid)
                        sudoku_solver(grid)
                        grid[row][col] = 0
                return


grid = np.array([[8, 1, 0, 0, 3, 0, 0, 2, 7],
                 [0, 6, 2, 0, 5, 0, 0, 9, 0],
                 [0, 7, 0, 0, 0, 0, 0, 0, 0],
                 [0, 9, 0, 6, 0, 0, 1, 0, 0],
                 [1, 0, 0, 0, 2, 0, 0, 0, 4],
                 [0, 0, 8, 0, 0, 5, 0, 7, 0],
                 [0, 0, 0, 0, 0, 0, 0, 8, 0],
                 [0, 2, 0, 0, 1, 0, 7, 5, 0],
                 [3, 8, 0, 0, 7, 0, 0, 4, 2]])
sudoku_solver(grid)

[[8 1 9 4 3 6 5 2 7]
 [4 6 2 7 5 1 3 9 8]
 [5 7 3 2 9 8 4 1 6]
 [2 9 4 6 8 7 1 3 5]
 [1 5 7 9 2 3 8 6 4]
 [6 3 8 1 4 5 2 7 9]
 [7 4 5 3 6 2 9 8 1]
 [9 2 6 8 1 4 7 5 3]
 [3 8 1 5 7 9 6 4 2]]
CPU times: user 465 ms, sys: 0 ns, total: 465 ms
Wall time: 466 ms
